### ISSUE TITLE
optimized functions drop generators when exceptions can be thrown

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1599]
All of the following is with `--abstractEffectsInAdditionalFunctions`.

This works:
```js
global.f = function(x, y) {
    if (y) Object.assign({}, x); else throw new Error();
};
__evaluatePureFunction(() => {
	global.f(__abstract(undefined, "x"), __abstract(undefined, "y"));
});
```

This doesn't work:
```js
global.f = function(x, y) {
    if (y) Object.assign({}, x); else throw new Error();
};

__optimize(f);
```

It produces the following, with no `Object.assign` in sight:
```js
(function () {
  var $$0 = {
    enumerable: false,
    configurable: true,
    writable: true
  };

  var _$1 = this;

  var _$2 = _$1.Error;
  var _$3 = _$2.prototype;
  var _$4 = _$1.Object;
  var _$5 = _$4.defineProperty;
  var _$6 = _$4.getPrototypeOf;

  var _0 = function (x, y) {
    var _1 = y;
    var _6 = _$3;

    var _4 = (__constructor.prototype = _6, new __constructor());

    $$0.value = "Error\n    at /tmp/test0.js:2:45", _$5(_4, "stack", $$0);

    if (_$6(_4) !== _6) {
      throw new Error("unexpected prototype");
    }

    if (_1) return void 0;else throw _4;
  };

  var __constructor = function () {};

  f = _0;
}).call(this);
```

(Also, why is the exception value `_4` always created along the main execution path? The `if` statement should defer to two generators referencing their relevant values so that the code generator can emit them in separate blocks.)

**Comment by cblappert** [comment]
> (Also, why is the exception value _4 always created along the main execution path? The if statement should defer to two generators referencing their relevant values so that the code generator can emit them in separate blocks.)

This is because I currently don't have a way of serializing the different branch's effects in their respective branches, I'll fix that with my `Effects` > `Generator` refactor

**Comment by cblappert** [comment]
Fixed and added as test case in #1602

**Comment by NTillmann** [comment]
Seems to work now (except, looking closely at the code generated from the example, there's still an issue #1627 which is now tracked separately).
